### PR TITLE
#156: truncate text on the left by default, but make it configurable

### LINKED ISSUE #156: Cut off left part of text, rather than right part of text when SVG is too small
Let's say your function is too wide to fit on the screen. Right now, the right side will be truncated:

```
for (var x = txt.length - 2; x > 0; x--) {
        if (t.getSubStringLength(0, x + 2) <= w) {
            t.textContent = txt.substring(0, x) + "..";
            return;
        }
    }
    t.textContent = "";
```

So e.g. in my case I have `/home/itamarst/Devel/memory-profiler/venv/lib64/python3.8/site-packages/numpy/core/numeric.py:ones` truncated to `/home/itamarst/Devel/memory-profiler/venv/lib64/..`.

But, you'll notice the most significant information is on the right side of that string: the function name, the main file, etc. It would be better to truncate it in the opposite direction: `../python3.8/site-packages/numpy/core/numeric.py:ones`, or at least have that as a rendering option.

### PR DESCRIPTION
**Pull request by itamarst**
Fixes #156.

I tested the flag manually, but suggestions for additional automated tests are welcome.

### CODE REVIEW

**Comment by jonhoo** [comment]
This looks good to me! Could you add a small test case for this too?

**Comment by itamarst** [comment]
One of the "read this file in, get this file out" kinda tests?

**Comment by itamarst** [comment]
That is, should it be the style of test in tests/flamegraph.rs, or something else? If the latter, what would it assert?

**Comment by jonhoo** [comment]
Yup, a read-in check-out test seems great for this!

**Comment by itamarst** [comment]
So I actually have to go and regenerate all the flamegraph SVGs in the integration tests, since they no longer match checked-in output... is there a utility to do that?

**Comment by jonhoo** [comment]
Ah, because you changed the default I suppose. I don't think so, but @jasonrhansen might have something handy? An alternative is to make the test suite continue to run with cropping on the right, and then just add one test that does cropping on the left.

**Comment by jasonrhansen** [comment]
If you delete the flamegraph SVGs, the tests will recreate them for you. You could do this, then `git diff` and make sure the new SVGs match the originals except for the truncation.

**Comment by itamarst** [comment]
Ok, I have:

1. Updated existing tests.
2. Added a new test.

**Comment by jonhoo** [comment]
Looks great to me, thanks!
Oh, could you please also submit a PR that updates `CHANGELOG.md` to point to these changes under "Unreleased"?

**Pull request merged**
