### PR TITLE
update dependendies (ahash, quick-xml)

### PR DESCRIPTION
**Pull request by crepererum**
Hey :wave: 

We're using your nice crate over at https://github.com/influxdata/influxdb_iox (indirectly via `pprof`) and I've seen that some of our the dependencies that `inferno` pulls are slightly outdated and hence get compiled twice. So I've decided to update them. :slightly_smiling_face:

### CODE REVIEW

**Review by jonhoo — APPROVED** [review]
Excellent, thanks for taking the time!

**Comment by jonhoo** [comment]
Unfortunately, it looks like some of the CI jobs fail :thinking: I'm guessing some of the formatting from `quick-xml` may have changed.

Separately, I noticed that `criterion` has also had a new release — would you mind including that in the PR?

**Comment by crepererum** [comment]
Working on it (probably needs a few iterations because I cannot get the tests to run locally (the `perf` and `dtrace` tests fail all the time and I don't really know why).

**Review by jonhoo — APPROVED** [review]
Excellent, thank you!

**Comment by jonhoo** [comment]
Looks like we have a couple of CI failures:

 - The `minimal-versions` one seems to be because we somehow now pull in `itoa 0.4.0`, which is _super_ old. Not sure why. If you run `cargo update -Zminimal-versions` and then `cargo tree -i itoa:0.4.0`, you may get some pointers to what's happened. That said, I'm fine merging even if that one is red. It _could_ be that merging from `main` will fix the problem for you.
 - The MSRV CI step (1.59.0) is because of a MSRV regression in `quick-xml`. It's been fixed upstream, but there hasn't been a release yet: https://github.com/tafia/quick-xml/pull/481#issuecomment-1262799455. I'd actually like to hold off on merging this PR until that lands (at which point we should bump the `quick-xml` dependency to `0.25.1`).
 - The `check / stable /fmt` CI step seems to complain about the lack of `cargo fmt` being applied to a line you changed — should be an easy fix!

**Comment by crepererum** [comment]
This is now solely blocked by the quick-xml release.

**Comment by jonhoo** [comment]
We should also do a bump of clap to major version 4, but I suppose it's no rush (and can be done in a separate PR).

**Comment by crepererum** [comment]
Updated to quick-xml 0.26 -- which fixes the MSRV. Let's do clap in another PR, also because this would mean that we compile two version of clap (at least for testing) because criterion still uses V3.

**Review by jonhoo — APPROVED** [review]

**Comment by jonhoo** [comment]
Ah, forgot the changelog! Would you mind updating that too?

**Comment by crepererum** [comment]
> Ah, forgot the changelog! Would you mind updating that too?

#273.

**Pull request merged**
