### PR TITLE
Remove demangle option from collapsers

### PR DESCRIPTION
**Pull request by jasonrhansen**
I think we should be able to remove `symbolic_demangle` as a dependency to help with #139. Doing so would also remove the following dependencies.
```
backtrace v0.3.37
backtrace-sys v0.1.31
cc v1.0.41
cpp_demangle v0.2.13
debugid v0.5.3
failure v0.1.5
failure_derive v0.1.5
glob v0.3.0
memmap v0.7.0
msvc-demangler v0.7.0
rustc-demangle v0.1.16
symbolic-common v6.1.4
symbolic-demangle v6.1.4
synstructure v0.10.2
uuid v0.7.4
```

#133 and #134 added to our collapsers the ability to fix partially demangled Rust symbols with no external dependencies. I originally implemented #132 to work around the same problem, but it required you to pass `--no-demangle` to perf script, or `-xmangled` to dtrace since `symbolic_demangle` doesn't work when the symbols are partially demangled. Now that we are able to take the mostly demangled symbols the profiling tools give us and fix them up from there, the `demangle` option on the collapsers seems to be unnecessary.

Do you think it makes sense to remove?

### CODE REVIEW

**Comment by jonhoo** [comment]
So, my only concern with this is if using `inferno` to produce flamegraphs for non-Rust code. The code we wrote is specific to Rust code (I believe)?

**Comment by jasonrhansen** [comment]
I believe `dtrace`, `perf`, and `sample` do a good job demangling C++ symbols. I don't know about Swift symbols, which is the other language `symbolic_demangle` can handle.

From what I can tell, Rust symbols are being handled by these tools as if they were C++ when demangling, which gets them close, but we have to fix them up from there.

**Comment by jonhoo** [comment]
Oh, I see what you mean -- we're still relying on the underlying tools to do _most_ of the demangling, and then just fixing it up ourselves. Yeah, I think I'm good with that then!

**Comment by jasonrhansen** [comment]
I'm not able to see the details on Azure Pipelines to see what  failed. If I click on the "View more details" link it says "Build not found." Any suggestions?

**Comment by jonhoo** [comment]
Hmm, I think you're running into https://github.com/xd009642/tarpaulin/issues/190, which I've also seen in the past. You can see the build pipeline here: https://dev.azure.com/jonhoo/jonhoo/_build/results?buildId=201&view=results. I'll try a re-run, which may invalidate that link. You _should_ always be able to see builds through https://dev.azure.com/jonhoo/jonhoo/_build?definitionId=10&_a=summary

**Comment by jasonrhansen** [comment]
Strange, now I'm able to get to everything just fine. Earlier I couldn't see any of the builds and I tried in multiple browsers. It's too bad tarpaulin keeps segfaulting.

**Comment by jonhoo** [comment]
Released in `0.9.0` :rocket:

**Pull request merged**
