### PR TITLE
Adjust height based on subtitle.

### LINKED ISSUE #159: Top-heavy flamegraphs hide the subtitle
If there's too long of a line at the top of the graph, the subtitle is hidden, probably because it ends up being covered up

For example:

1. If the top line is very long: `echo "hello 1" | inferno-flamegraph --subtitle "Hello! this is a subtitle" > regular.svg`

2. If the top line is very long because it's an inverted graph: `cat flamegraph/test/results/perf-java-stacks-01-collapsed-pid.txt | inferno-flamegraph --subtitle "Hello! this is a subtitle"  --inverted > inverted.svg`

### PR DESCRIPTION
**Pull request by itamarst**
Fixes #159.

To test, rerun the two commands in #159 and notice if subtitle is visible.

### CODE REVIEW

**Comment by jonhoo** [comment]
Interesting.. Do you have a reference to the corresponding code in the flamegraph codebase? I just want to make sure that we do the same thing they do.

**Comment by itamarst** [comment]
I find the automated tools claim that coverage has gone down rather implausible, but if this is important I can find something else to test :grinning:

**Comment by itamarst** [comment]
As I mentioned, the approach taken by the Perl version is wrong in one case. However, they do have some code in there:

```perl
my $ypad1 = $fontsize * 3;      # pad top, include title
my $ypad2 = $fontsize * 2 + 10; # pad bottom, include labels
my $ypad3 = $fontsize * 2;      # pad top, include subtitle (optional)

...
$imageheight += $ypad3 if $subtitletext ne "";
```

**Comment by jonhoo** [comment]
Haha, no, you're all good. There's some variance in there that sometimes triggers weird false positives. Looks good to me!

And thanks for the perl reference: the change looks sensible :+1:

**Comment by jonhoo** [comment]
Oh, and thanks for the quick fix! <3

**Comment by jonhoo** [comment]
Released as `0.9.4`.

**Pull request merged**
