### PR TITLE
do not reallocate start event

### PR DESCRIPTION
**Pull request by andy128k**
The same as https://github.com/jonhoo/inferno/pull/108 but without changing interfaces

### CODE REVIEW

**Comment by jonhoo** [comment]
Oooh, that's interesting... This might be something we could do with the other caches too so we don't have to pass them around everywhere. Thoughts @jasonrhansen? I kind of like it!

**Comment by jasonrhansen** [comment]
I like this for `write_str` since it gets called from several different places. The other caches wouldn't really benefit. The only other function we have that takes one is `filled_rectangle`, but it's only called from one place.

**Comment by jonhoo** [comment]
@andy128k I'd be happy to merge something like this. Could you re-apply this change on top of master since I merged #108 before you filed this?

**Comment by andy128k** [comment]
@jonhoo Done

**Comment by jonhoo** [comment]
@andy128k oh, looks like rustfmt [complained](https://travis-ci.com/jonhoo/inferno/jobs/186827251). should be a quick fix.

**Comment by jonhoo** [comment]
:heart:

**Pull request merged**
